### ISSUE TITLE
How to get my printer address

### ISSUE THREAD

**Issue by andylim-mkj** [lemoine-yann/SimpleEscPos.Net#1]
Hi,
1. How to get my printer address from a .net maui mobile (Android/IOS)?
2. In Windows Machine, how to use the samba address (e.g:\\localhost\myPrinterSharedName). What Port no should be used?
Thanks

**Comment by lemoine-yann** [comment]
1 - I'm not sure if this is possible directly from .NET MAUI on mobile (Android/iOS). You might need to use the specific SDK for your printer to access its address and functionalities.

2 - On Windows, you can install the printer using the generic network port driver. Then, share the printer to access it via a path like \\\\127.0.0.1\myPrinter. To send commands to the printer, you can use a simple file copy. For example, in the command prompt (MS-DOS):

copy mycommands.txt \\\\127.0.0.1\myprinter

In C# use System.IO.File
